# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56e6ecc0490a5162fd9e85e4118d7563c93416088bafc51453b26b2409b3da3525bc893484b655512893bcd3ee1afd7ae23ab014515326bacc88f54a5e6c52c9

test:
  secret_key_base: ea2a9573d40a110a79171fe73f4c9a8c04b9a798fa5ac7d787821ea77d6ed0c240dcca715db7add03e25570869afba1ba5523b912e96401559e10b095c80977b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
